name: Deploy Lambda

on:
  push:
    branches: [ main ]
    paths:
      - 'index.mjs'
      - 'package.json'
      - '.github/workflows/deploy-lambda.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        
    - name: Deploy to Lambda
      run: |
        # Create deployment package
        zip -r lambda-deployment.zip index.mjs package.json node_modules/
        
        # Update Lambda function code
        aws lambda update-function-code \
          --function-name color-report-lambda \
          --zip-file fileb://lambda-deployment.zip \
          --region us-east-2
          
        # Update Lambda function configuration (if needed)
        aws lambda update-function-configuration \
          --function-name color-report-lambda \
          --environment Variables='{"BUCKET":"color-reports-assets","OPENAI_API_KEY":"${{ secrets.OPENAI_API_KEY }}"}'
          
        echo "Lambda deployment completed!" 